steps:
  - label: ":golang:"
    plugins:
      golang-cross-compile#v1.3.0:
        build: ./cmd/bk
        import: github.com/buildkite/cli
        targets:
          - version: "1.11"
            goos: linux
            goarch: amd64
            gomodule: "on"
