steps:
  - label: ":golang: build"
    plugins:
      golang-cross-compile#74f9522:
        debug: true
        build: ./cmd/bk
        import: github.com/buildkite/cli
        targets:
          - version: 1.10.3
            goos: linux
            goarch: amd64
          - version: 1.10.3
            goos: windows
            goarch: amd64
          - version: 1.10.3
            goos: darwin
            arch: amd64
          - version: 1.10.3
            goos: freebsd
            goarch: amd64
